# Generated by Django 5.2.5 on 2025-08-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('first_game', 'First Game'), ('score_1K', '1,000 Points'), ('score__5k', '5,000 Points'), ('score_10k', '10,000 Points'), ('score_25k', '25,000 Points'), ('level_5', 'Level 5'), ('level_10', 'Level 10'), ('lines_100', '100 Lines'), ('lines_500', '500 Lines'), ('games_10', '10 Games'), ('games_50', '50 Games'), ('tetris_master', 'Tetris Master')], max_length=20)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('score_when_earned', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_score', models.IntegerField(default=0)),
                ('current_level', models.IntegerField(default=1)),
                ('current_lines', models.IntegerField(default=0)),
                ('board_state', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('level', models.IntegerField()),
                ('lines_cleared', models.IntegerField()),
                ('duration', models.IntegerField(blank=True, help_text='Game duration in seconds', null=True)),
                ('date_played', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['score', '-date_played'],
            },
        ),
    ]
