# Generated by Django 5.2.5 on 2025-08-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='player_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
