# Generated by Django 5.2.5 on 2025-08-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_player_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='player_level',
            field=models.IntegerField(default=1),
        ),
    ]
